from .admin_views import *
from .employee_views import *
from .technologist_views import *
from .common_views import *
from .cutter_views import *
from .qc_views import *
from .packer_views import *
from .keeper_views import *
from .accountant_views import *
from .sub_tech_view import *
from .barcode_views import *
from .whatsapp_qr_views import *