# Generated by Django 5.0.3 on 2024-09-21 23:02

import django.db.models.deletion
import django.utils.timezone
import production.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=50)),
                ('key', models.CharField(blank=True, max_length=100, null=True)),
                ('value', models.CharField(blank=True, max_length=100, null=True)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
            ],
        ),
        migrations.CreateModel(
            name='AssignedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('start_time', models.DateTimeField(blank=True, null=True, verbose_name='Время начала')),
                ('end_time', models.DateTimeField(blank=True, null=True, verbose_name='Время окончания')),
                ('is_success', models.BooleanField(default=False, verbose_name='Завершено успешно')),
                ('payment_date', models.DateField(null=True, verbose_name='Дата оплаты')),
            ],
        ),
        migrations.CreateModel(
            name='Branch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact_info', models.TextField(verbose_name='Контактная информация')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
            ],
        ),
        migrations.CreateModel(
            name='Cut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(editable=False, verbose_name='Номер')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Дата')),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
            ],
        ),
        migrations.CreateModel(
            name='Fabrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='№ узла')),
                ('is_common', models.BooleanField(default=False, verbose_name='Общий')),
                ('type', models.IntegerField(choices=[(0, 'Шитье'), (1, 'Резка'), (2, 'ОТК'), (3, 'Упаковка')], default=0, verbose_name='Тип')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
            ],
        ),
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assortments', to='production.branch', verbose_name='Филиал')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('order_number', models.CharField(max_length=100, verbose_name='Номер заказа')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('status', models.IntegerField(choices=[(0, 'Новый'), (1, 'В процессе'), (2, 'Завершен')], default=0, verbose_name='Статус')),
                ('term', models.DateField(default=production.models.ClientOrder.default_term, verbose_name='Срок выполнения')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='production.branch', verbose_name='Филиал')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='client_orders', to='production.client', verbose_name='Клиент')),
            ],
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('width', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Ширина')),
                ('length', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Длина')),
                ('factual', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Фактическое')),
                ('commerce', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Коммерческое')),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.cut', verbose_name='Крой')),
                ('fabrics', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consumptions', to='production.fabrics', verbose_name='Ткани')),
            ],
        ),
        migrations.CreateModel(
            name='FixedSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Зарплата')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_salaries', to='production.branch', verbose_name='Филиал')),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('assortment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='models', to='production.assortment', verbose_name='Ассортимент')),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='Название')),
                ('number', models.CharField(blank=True, max_length=100, null=True, verbose_name='№ПП')),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Оплата')),
                ('preferred_completion_time', models.IntegerField(verbose_name='Предпочтительное время выполнения')),
                ('average_completion_time', models.IntegerField(null=True, verbose_name='Среднее время выполнения')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='operation_photos/', verbose_name='Фото')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.equipment', verbose_name='Оборудование')),
                ('node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.node', verbose_name='Узел')),
            ],
        ),
        migrations.CreateModel(
            name='ModelOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.model')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.operation')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='model',
            name='operations',
            field=models.ManyToManyField(related_name='models', through='production.ModelOperation', to='production.operation', verbose_name='Операции'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(0, 'Новый'), (1, 'В процессе'), (2, 'Завершен')], default=0, verbose_name='Статус')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('completed_quantity', models.IntegerField(default=0, verbose_name='Завершенное количество')),
                ('payment', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Оплата')),
                ('client_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.clientorder', verbose_name='Заказ клиента')),
                ('colors', models.ManyToManyField(blank=True, related_name='orders', to='production.color', verbose_name='Цвета')),
                ('fabrics', models.ManyToManyField(blank=True, related_name='orders', to='production.fabrics', verbose_name='Ткани')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.model', verbose_name='Модель')),
            ],
        ),
        migrations.AddField(
            model_name='cut',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuts', to='production.order', verbose_name='Заказ'),
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер')),
                ('layers', models.DecimalField(blank=True, decimal_places=0, max_digits=10, null=True, verbose_name='Слои')),
                ('meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Метры')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Паспорт завершен')),
                ('cut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='production.cut', verbose_name='Крой')),
            ],
        ),
        migrations.CreateModel(
            name='PassportSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(blank=True, max_length=5, null=True)),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('stage', models.IntegerField(choices=[(0, 'Резка'), (1, 'Шитье'), (2, 'ОТК'), (3, 'Упаковка'), (4, 'Готово')], default=0, verbose_name='Этап')),
                ('passport', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport_sizes', to='production.passport', verbose_name='Паспорт')),
            ],
        ),
        migrations.CreateModel(
            name='ProductionPiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('piece_number', models.IntegerField(verbose_name='Piece Number')),
                ('stage', models.CharField(choices=[('NOT_CHECKED', 'Непроверено'), ('CHECKED', 'Проверено'), ('PACKED', 'Упаковано'), ('DEFECT', 'Брак')], default='NOT_CHECKED', max_length=20, verbose_name='Stage')),
                ('defect_type', models.CharField(blank=True, choices=[('STITCHING', 'Ошибка шитья'), ('CUTTING', 'Ошибка резки'), ('FABRIC', 'Дефект ткани'), ('ASSEMBLY', 'Ошибка сборки'), ('OTHER', 'Прочие ошибки')], max_length=20, null=True, verbose_name='Defect Type')),
                ('passport_size', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pieces', to='production.passportsize')),
            ],
        ),
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('DEFECT', 'Дефект'), ('DISCREPANCY', 'Расхождение')], max_length=20, verbose_name='Тип ошибки')),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Стоимость')),
                ('status', models.CharField(choices=[('REPORTED', 'Сообщено'), ('UNRESOLVABLE', 'Неразрешимо'), ('RESOLVED', 'Разрешено')], default='REPORTED', max_length=20, verbose_name='Статус')),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата сообщения')),
                ('resolved_date', models.DateTimeField(blank=True, null=True, verbose_name='Дата решения')),
                ('piece', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='production.productionpiece', verbose_name='Единица')),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Ширина')),
                ('meters', models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Метры')),
                ('used_meters', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True, verbose_name='Использованные метры')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.branch', verbose_name='Филиал')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.color', verbose_name='Цвет')),
                ('fabrics', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.fabrics', verbose_name='Ткань')),
            ],
        ),
        migrations.AddField(
            model_name='passport',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport_rolls', to='production.roll', verbose_name='Рулон'),
        ),
        migrations.CreateModel(
            name='SizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.color', verbose_name='Цвет')),
            ],
        ),
        migrations.AddField(
            model_name='passportsize',
            name='size_quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passport_sizes', to='production.sizequantity', verbose_name='Размер и количество'),
        ),
        migrations.AddField(
            model_name='passport',
            name='size_quantities',
            field=models.ManyToManyField(related_name='passports', through='production.PassportSize', to='production.sizequantity', verbose_name='Размеры и количества'),
        ),
        migrations.AddField(
            model_name='order',
            name='size_quantities',
            field=models.ManyToManyField(related_name='orders', to='production.sizequantity', verbose_name='Размеры и количества'),
        ),
        migrations.AddField(
            model_name='cut',
            name='size_quantities',
            field=models.ManyToManyField(related_name='cuts', to='production.sizequantity', verbose_name='Размеры и количества'),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=100, verbose_name='ID сотрудника')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('fingerprint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Browser Fingerprint')),
                ('type', models.IntegerField(choices=[(0, 'Администратор'), (1, 'Технолог'), (2, 'Сотрудник'), (3, 'Закройщик'), (4, 'ОТК'), (5, 'Упаковщик'), (6, 'Кладовщик')], default=2, verbose_name='Тип')),
                ('status', models.BooleanField(default=False, verbose_name='Статус')),
                ('station', models.CharField(choices=[('admin_technologist', 'Админ/Технолог'), ('cutting_station', 'Закройный участок'), ('sewing_station', 'Швейный участок'), ('ironing_station', 'Утюжный участок'), ('quality_control', 'ОТК'), ('package', 'Упаковка'), ('warehouse', 'Склад'), ('interns', 'Практиканты'), ('others', 'Остальные')], default='sewing_station', max_length=100, verbose_name='Станция')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='production.branch', verbose_name='Филиал')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(verbose_name='Дата платежа')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('fixed_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='production.fixedsalary', verbose_name='Оклад')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='production.userprofile', verbose_name='Сотрудник')),
            ],
        ),
        migrations.CreateModel(
            name='ReassignedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassigned_quantity', models.IntegerField(verbose_name='Переназначенное количество')),
                ('reason', models.TextField(blank=True, null=True, verbose_name='Причина')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Завершено')),
                ('is_success', models.BooleanField(default=False, verbose_name='Завершено успешно')),
                ('payment_date', models.DateField(null=True, verbose_name='Дата оплаты')),
                ('original_assigned_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='production.assignedwork', verbose_name='Исходное назначенное задание')),
                ('new_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassigned_works', to='production.userprofile', verbose_name='Новый сотрудник')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.userprofile', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='fixedsalary',
            name='employees',
            field=models.ManyToManyField(related_name='fixed_salaries', to='production.userprofile', verbose_name='Сотрудники'),
        ),
        migrations.CreateModel(
            name='ErrorResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Процент ответственности, приписываемый этому сотруднику.', max_digits=5, verbose_name='Процент ответственности')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_responsibilities', to='production.error', verbose_name='Ошибка')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_responsibilities', to='production.userprofile', verbose_name='Сотрудник')),
            ],
        ),
        migrations.AddField(
            model_name='error',
            name='responsible_employees',
            field=models.ManyToManyField(through='production.ErrorResponsibility', to='production.userprofile', verbose_name='Ответственные сотрудники'),
        ),
        migrations.CreateModel(
            name='EmployeeAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_clock_in', models.BooleanField(default=False)),
                ('distance', models.FloatField(blank=True, null=True, verbose_name='Distance from Workplace (meters)')),
                ('fingerprint', models.CharField(blank=True, max_length=255, null=True, verbose_name='Browser Fingerprint')),
                ('branch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='production.branch')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='production.userprofile', verbose_name='Сотрудник'),
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employees', models.ManyToManyField(through='production.AssignedWork', to='production.userprofile', verbose_name='Сотрудники')),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='production.operation', verbose_name='Операция')),
                ('passport_size', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='production.passportsize', verbose_name='Размер и количество')),
            ],
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_works', to='production.work', verbose_name='Работа'),
        ),
        migrations.AddConstraint(
            model_name='userprofile',
            constraint=models.UniqueConstraint(fields=('employee_id', 'branch'), name='unique_employee_id_per_branch'),
        ),
    ]
