# Generated by Django 5.0.3 on 2024-03-15 17:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assortment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(max_length=50)),
                ('fabrics', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('employee_id', models.CharField(max_length=100, unique=True)),
                ('type', models.CharField(choices=[('Employee', 'Employee'), ('Technologist', 'Technologist'), ('Admin', 'Admin')], max_length=12)),
                ('status', models.BooleanField(default=False)),
                ('station', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equipment', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('preferred_completion_time', models.DurationField()),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.model')),
            ],
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('size', models.CharField(max_length=50)),
                ('quantity', models.IntegerField()),
                ('operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='production.operation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='production.user')),
            ],
        ),
        migrations.CreateModel(
            name='Passport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('assortment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='production.assortment')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='production.client')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='production.model')),
                ('operations', models.ManyToManyField(related_name='passports', to='production.operation')),
                ('roll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='production.roll')),
                ('works', models.ManyToManyField(related_name='passports', to='production.work')),
            ],
        ),
    ]
