# Generated by Django 5.0.3 on 2024-04-18 06:04

import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='term',
        ),
        migrations.AddField(
            model_name='clientorder',
            name='term',
            field=models.DateField(default=production.models.ClientOrder.default_term),
        ),
    ]
