# Generated by Django 5.0.3 on 2024-09-16 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='color',
        ),
        migrations.AddField(
            model_name='order',
            name='colors',
            field=models.ManyToManyField(blank=True, related_name='orders', to='production.color', verbose_name='Цвета'),
        ),
        migrations.RemoveField(
            model_name='order',
            name='fabrics',
        ),
        migrations.AddField(
            model_name='order',
            name='fabrics',
            field=models.ManyToManyField(blank=True, related_name='orders', to='production.fabrics', verbose_name='Ткани'),
        ),
    ]
