# Generated by Django 5.0.3 on 2024-04-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='operation_photos/'),
        ),
    ]
