# Generated by Django 5.0.3 on 2024-03-16 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_alter_work_user_userprofile_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Admin'), (1, 'Technologist'), (2, 'Employee')], default=2),
        ),
    ]
