# Generated by Django 5.0.3 on 2024-09-16 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_order_color_order_colors_remove_order_fabrics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='station',
            field=models.CharField(choices=[('admin_technologist', 'Админ/Технолог'), ('cutting_station', 'Закройный участок'), ('sewing_station', 'Швейный участок'), ('ironing_station', 'Утюжный участок'), ('quality_control', 'ОТК'), ('package', 'Упаковка'), ('warehouse', 'Склад'), ('interns', 'Практиканты'), ('others', 'Остальные')], default='sewing_station', max_length=100, verbose_name='Станция'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Технолог'), (2, 'Сотрудник'), (3, 'Закройщик'), (4, 'ОТК'), (5, 'Упаковщик'), (6, 'Кладовщик')], default=2, verbose_name='Тип'),
        ),
    ]
