# Generated by Django 5.0.3 on 2024-04-18 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_remove_order_term_clientorder_term'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Defects',
            new_name='Defect',
        ),
    ]
