# Generated by Django 5.0.3 on 2024-10-07 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_phonenumberscaner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='is_common',
        ),
    ]
