# Generated by Django 5.0.3 on 2024-04-08 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_operation_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReassignedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reassigned_quantity', models.IntegerField()),
                ('reason', models.TextField(blank=True, null=True)),
                ('new_employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassigned_works', to='production.userprofile')),
                ('original_assigned_work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reassignments', to='production.assignedwork')),
            ],
        ),
    ]
