# Generated by Django 5.0.3 on 2024-10-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_remove_node_is_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='model_photos/', verbose_name='Фото'),
        ),
    ]
