# Generated by Django 5.0.3 on 2024-04-20 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_rename_defects_defect'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Completed')], default=0),
        ),
        migrations.AlterField(
            model_name='defect',
            name='status',
            field=models.CharField(choices=[('REPORTED', 'Reported'), ('UNRESOLVABLE', 'Unresolvable'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=20),
        ),
    ]
