# Generated by Django 5.0.3 on 2024-04-09 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_reassignedwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassignedwork',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='Completed Successfully'),
        ),
    ]
