# Generated by Django 5.0.3 on 2024-03-17 09:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_alter_userprofile_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='production.userprofile'),
        ),
    ]
