# Generated by Django 5.0.3 on 2024-10-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_model_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='branch',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='branch',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Longitude'),
        ),
        migrations.AddField(
            model_name='branch',
            name='radius',
            field=models.IntegerField(blank=True, null=True, verbose_name='Allowed Radius (meters)'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=15, null=True, verbose_name='Longitude'),
        ),
    ]
