# Generated by Django 5.0.3 on 2024-09-19 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_phonenumberscaner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumberscaner',
            old_name='phone_number',
            new_name='mobile_number',
        ),
    ]
