# Generated by Django 5.0.3 on 2024-04-09 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_reassignedwork_is_success'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassignedwork',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
    ]
