# Generated by Django 5.0.3 on 2024-03-17 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_alter_operation_preferred_completion_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='preferred_completion_time',
            field=models.IntegerField(),
        ),
    ]
