# Generated by Django 5.0.3 on 2024-09-18 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=100)),
                ('accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='production.accessory')),
            ],
        ),
    ]
