# Generated by Django 5.0.3 on 2024-04-20 15:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_clientorder_status_alter_defect_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defect',
            name='order',
        ),
        migrations.AddField(
            model_name='defect',
            name='passport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='defects', to='production.passport'),
        ),
    ]
