# Generated by Django 5.0.3 on 2024-09-18 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_accessoryattribute'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessoryAttribute',
        ),
    ]
