# Generated by Django 5.0.3 on 2024-11-01 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_branch_latitude_branch_longitude_branch_radius_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='size_quantities',
        ),
        migrations.AddField(
            model_name='cut',
            name='old_size_quantities',
            field=models.ManyToManyField(related_name='old_cuts', to='production.sizequantity', verbose_name='Старые размеры и количества'),
        ),
    ]
