# Generated by Django 5.0.3 on 2024-04-21 07:05

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_remove_defect_order_defect_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportsize',
            name='stage',
            field=models.IntegerField(choices=[(0, 'Cutting'), (1, 'Sewing'), (2, 'Quality Control'), (3, 'Packing'), (4, 'Done')], default=0),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Технолог'), (2, 'Сотрудник'), (3, 'Закройщик'), (4, 'ОТК'), (5, 'Упаковщик')], default=2),
        ),
        migrations.CreateModel(
            name='Discrepancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(help_text='Use negative values for deficiencies and positive for excess.')),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNRESOLVABLE', 'Unresolvable'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=20)),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='production.passport')),
                ('size_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancies', to='production.sizequantity')),
            ],
        ),
    ]
