# Generated by Django 5.0.3 on 2024-03-17 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_operation_preferred_completion_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passport',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
