# Generated by Django 5.0.3 on 2024-04-22 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_passportsize_stage_alter_userprofile_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedSalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(max_length=100)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employees', models.ManyToManyField(related_name='fixed_salaries', to='production.userprofile')),
            ],
        ),
    ]
