# Generated by Django 5.0.3 on 2024-09-18 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_delete_accessoryattribute'),
    ]

    operations = [
        migrations.AddField(
            model_name='accessory',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='accessory',
            name='key',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='accessory',
            name='value',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
