# Generated by Django 5.0.3 on 2024-03-17 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_alter_passport_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='operations',
        ),
    ]
