# Generated by Django 5.0.3 on 2024-11-01 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0006_remove_cut_size_quantities_cut_old_size_quantities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='old_size_quantities',
        ),
        migrations.CreateModel(
            name='CutSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extra', models.CharField(blank=True, max_length=5, null=True, verbose_name='Дополнительно')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('stage', models.IntegerField(choices=[(0, 'Резка'), (1, 'Шитье'), (2, 'ОТК'), (3, 'Упаковка'), (4, 'Готово')], default=0, verbose_name='Этап')),
                ('cut', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_sizes', to='production.cut', verbose_name='Резка')),
                ('size_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cut_sizes', to='production.sizequantity', verbose_name='Размер и количество')),
            ],
        ),
        migrations.AddField(
            model_name='cut',
            name='size_quantities',
            field=models.ManyToManyField(related_name='cuts', through='production.CutSize', to='production.sizequantity', verbose_name='Размеры и количества'),
        ),
    ]
