# Generated by Django 5.0.3 on 2024-11-01 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_remove_cut_old_size_quantities_cutsize_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutsize',
            name='quantity',
        ),
    ]
