# Generated by Django 5.0.3 on 2024-04-10 15:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_assortment_branch_employeeattendance_branch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='assortment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.assortment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.model'),
        ),
        migrations.AlterField(
            model_name='order',
            name='roll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.roll'),
        ),
    ]
