# Generated by Django 5.0.3 on 2024-04-22 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_fixedsalary'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
    ]
