# Generated by Django 5.0.3 on 2024-09-18 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_accessory_info_accessory_key_accessory_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizequantity',
            name='color',
        ),
    ]
