# Generated by Django 5.0.3 on 2024-03-18 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0007_remove_passport_operations'),
    ]

    operations = [
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='work',
            name='size',
        ),
        migrations.AddField(
            model_name='model',
            name='sizes',
            field=models.ManyToManyField(related_name='models', to='production.size'),
        ),
    ]
