# Generated by Django 5.0.3 on 2024-03-18 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_size_remove_work_size_model_sizes'),
    ]

    operations = [
        migrations.CreateModel(
            name='SizeQuantity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10)),
                ('quantity', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='model',
            name='sizes',
        ),
        migrations.AddField(
            model_name='passport',
            name='size_quantities',
            field=models.ManyToManyField(related_name='passports', to='production.sizequantity'),
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
