# Generated by Django 5.0.3 on 2024-11-01 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_remove_cutsize_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='cut',
        ),
        migrations.AddField(
            model_name='passport',
            name='cut_size',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='production.cutsize', verbose_name='Крой размер'),
        ),
    ]
