# Generated by Django 5.0.3 on 2024-04-11 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_alter_order_assortment_alter_order_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assortment',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assortments', to='production.branch'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_attendances', to='production.branch'),
        ),
        migrations.AlterField(
            model_name='order',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.branch'),
        ),
        migrations.AlterField(
            model_name='roll',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.branch'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='branch',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_profiles', to='production.branch'),
        ),
    ]
