# Generated by Django 5.0.3 on 2024-09-18 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_remove_sizequantity_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizequantity',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.color', verbose_name='Цвет'),
        ),
    ]
