# Generated by Django 5.0.3 on 2024-04-22 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0008_operation_is_common'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='is_common',
        ),
        migrations.AddField(
            model_name='node',
            name='is_common',
            field=models.BooleanField(default=False),
        ),
    ]
