# Generated by Django 5.0.3 on 2024-04-22 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_remove_operation_is_common_node_is_common'),
    ]

    operations = [
        migrations.AddField(
            model_name='node',
            name='type',
            field=models.IntegerField(choices=[(0, 'Sewing'), (1, 'Cuttng'), (2, 'Quality Control'), (3, 'Packing')], default=0),
        ),
        migrations.AddField(
            model_name='operation',
            name='employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.userprofile'),
        ),
    ]
