# Generated by Django 5.0.3 on 2024-03-18 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_sizequantity_remove_model_sizes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='works',
        ),
        migrations.AddField(
            model_name='work',
            name='passport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='production.passport'),
        ),
    ]
