# Generated by Django 5.0.3 on 2024-11-01 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0009_remove_passport_cut_passport_cut_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='cut_size',
        ),
        migrations.AddField(
            model_name='passport',
            name='cut',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='production.cut', verbose_name='Крой'),
        ),
    ]
