# Generated by Django 5.0.3 on 2024-03-18 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_remove_passport_works_work_passport'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='size_quantity',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='works', to='production.sizequantity'),
        ),
        migrations.AlterField(
            model_name='work',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='work',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
