# Generated by Django 5.0.3 on 2024-04-23 05:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_node_type_operation_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operation',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='operations', to='production.userprofile'),
        ),
    ]
