# Generated by Django 5.0.3 on 2024-11-06 01:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0010_remove_passport_cut_size_passport_cut'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Accessory',
        ),
    ]
