# Generated by Django 5.0.3 on 2024-04-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_alter_operation_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedwork',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Half Paid'), (2, 'Fully Paid')], default=0),
        ),
    ]
