# Generated by Django 5.0.3 on 2024-03-18 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_work_size_quantity_alter_work_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='quantity',
        ),
    ]
