# Generated by Django 5.0.3 on 2024-11-06 01:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0011_delete_accessory'),
    ]

    operations = [
        migrations.CreateModel(
            name='AbstractAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название')),
                ('unit', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AccessoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100, verbose_name='Key')),
                ('value', models.CharField(max_length=100, verbose_name='Value')),
            ],
        ),
        migrations.CreateModel(
            name='Accessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10)),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='accessories', to='production.abstractaccessory', verbose_name='Фурнитура')),
                ('attributes', models.ManyToManyField(related_name='accessories', to='production.accessoryattribute')),
            ],
        ),
    ]
