# Generated by Django 5.0.3 on 2024-04-25 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_assignedwork_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='reassignedwork',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Half Paid'), (2, 'Fully Paid')], default=0),
        ),
    ]
