# Generated by Django 5.0.3 on 2024-11-06 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0012_abstractaccessory_accessoryattribute_accessory'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractaccessory',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is Archived'),
        ),
    ]
