# Generated by Django 5.0.3 on 2024-04-27 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_reassignedwork_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedwork',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid')], default=0),
        ),
        migrations.AlterField(
            model_name='operation',
            name='name',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='reassignedwork',
            name='payment_status',
            field=models.IntegerField(choices=[(0, 'Pending'), (1, 'Paid')], default=0),
        ),
    ]
