# Generated by Django 5.0.3 on 2024-03-25 12:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_employeeattendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.userprofile'),
        ),
    ]
