# Generated by Django 5.0.3 on 2024-11-06 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0013_abstractaccessory_is_archived'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelAccessory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('abstract_accessory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_accessories', to='production.abstractaccessory')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='model_accessories', to='production.model')),
            ],
        ),
        migrations.AddField(
            model_name='model',
            name='abstract_accessories',
            field=models.ManyToManyField(related_name='models', through='production.ModelAccessory', to='production.abstractaccessory', verbose_name='Фурнитура'),
        ),
    ]
