# Generated by Django 5.0.3 on 2024-11-08 08:24

import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_modelaccessory_model_abstract_accessories'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Information'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='launch',
            field=models.DateField(blank=True, default=production.models.ClientOrder.default_term, null=True, verbose_name='Начало выполнения'),
        ),
    ]
