# Generated by Django 5.0.3 on 2024-04-27 15:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_alter_assignedwork_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 15, 45, 11, 259343, tzinfo=datetime.timezone.utc)),
        ),
    ]
