# Generated by Django 5.0.3 on 2024-03-25 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0014_alter_employeeattendance_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=100, unique=True)),
                ('quantity', models.IntegerField()),
                ('status', models.IntegerField(choices=[(0, 'New'), (1, 'In Progress'), (2, 'Completed')], default=0)),
                ('completed_quantity', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.client')),
                ('passports', models.ManyToManyField(related_name='orders', to='production.passport')),
            ],
        ),
    ]
