# Generated by Django 5.0.3 on 2024-03-25 15:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='passports',
        ),
        migrations.AddField(
            model_name='passport',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='production.order'),
        ),
    ]
