# Generated by Django 5.0.3 on 2024-11-08 08:35

import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_clientorder_info_clientorder_launch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='launch',
            field=models.DateField(blank=True, default=production.models.ClientOrder.default_launch, null=True, verbose_name='Начало выполнения'),
        ),
    ]
