# Generated by Django 5.0.3 on 2024-04-27 15:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0015_clientorder_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
