# Generated by Django 5.0.3 on 2024-04-28 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_alter_clientorder_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignedwork',
            name='payment_status',
        ),
        migrations.RemoveField(
            model_name='reassignedwork',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='reassignedwork',
            name='payment_date',
            field=models.DateField(null=True),
        ),
        migrations.CreateModel(
            name='SalaryPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='production.userprofile')),
                ('fixed_salary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salary_payments', to='production.fixedsalary')),
            ],
        ),
    ]
