# Generated by Django 5.0.3 on 2024-03-25 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_remove_order_passports_passport_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passport',
            name='assortment',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='client',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='model',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='roll',
        ),
        migrations.AddField(
            model_name='order',
            name='assortment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.assortment'),
        ),
        migrations.AddField(
            model_name='order',
            name='model',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.model'),
        ),
        migrations.AddField(
            model_name='order',
            name='roll',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.roll'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_number',
            field=models.CharField(max_length=100),
        ),
    ]
