# Generated by Django 5.0.3 on 2024-11-25 08:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0016_alter_clientorder_launch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'В процессе'), (2, 'Завершен'), (3, 'Отправлен')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'В процессе'), (2, 'Завершен'), (3, 'Отправлен')], default=0, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Технолог'), (2, 'Сотрудник'), (3, 'Закройщик'), (4, 'ОТК'), (5, 'Упаковщик'), (6, 'Кладовщик'), (7, 'Менеджер')], default=2, verbose_name='Тип'),
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Warehouse Name')),
                ('location', models.TextField(verbose_name='Location')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('responsible_person', models.ForeignKey(blank=True, limit_choices_to={'type': 7}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.userprofile', verbose_name='Responsible Person')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('available_quantity', models.IntegerField(default=0, verbose_name='Available Quantity')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='Sold Quantity')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production.model', verbose_name='Model')),
                ('size_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production.sizequantity', verbose_name='Size Quantity')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='production.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'verbose_name': 'Stock',
                'verbose_name_plural': 'Stocks',
                'unique_together': {('warehouse', 'size_quantity')},
            },
        ),
    ]
