# Generated by Django 5.0.3 on 2024-11-25 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_alter_clientorder_status_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='warehouse',
            name='location',
            field=models.TextField(blank=True, null=True, verbose_name='Location'),
        ),
    ]
