# Generated by Django 5.0.3 on 2024-03-26 13:27

import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_remove_passport_assortment_remove_passport_client_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='term',
            field=models.DateField(default=production.models.Order.default_term),
        ),
    ]
