# Generated by Django 5.0.3 on 2024-04-28 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0017_remove_assignedwork_payment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fixedsalary',
            name='branch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fixed_salaries', to='production.branch'),
        ),
    ]
