# Generated by Django 5.0.3 on 2025-02-10 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_alter_abstractaccessory_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorder',
            name='order_number',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
    ]
