# Generated by Django 5.0.3 on 2024-04-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_fixedsalary_branch'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='station',
            field=models.CharField(choices=[('admin_technologist', 'Админ/Технолог'), ('cutting_station', 'Закройный участок'), ('sewing_station', 'Швейный участок'), ('ironing_station', 'Утюжный участок'), ('quality_control', 'ОТК'), ('package', 'Упаковка'), ('interns', 'Практиканты'), ('others', 'Остальные')], default='sewing_station', max_length=100),
        ),
    ]
