# Generated by Django 5.0.3 on 2025-02-15 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0018_alter_abstractaccessory_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='cut',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='cut',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ширина'),
        ),
        migrations.AddField(
            model_name='sizequantity',
            name='fabrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.fabrics', verbose_name='Ткань'),
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='order_number',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='station',
            field=models.CharField(blank=True, choices=[('admin_technologist', 'Админ/Технолог'), ('cutting_station', 'Закройный участок'), ('sewing_station', 'Швейный участок'), ('ironing_station', 'Утюжный участок'), ('quality_control', 'ОТК'), ('package', 'Упаковка'), ('warehouse', 'Склад'), ('interns', 'Практиканты'), ('others', 'Остальные')], default='sewing_station', max_length=100, null=True, verbose_name='Станция'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Статус'),
        ),
    ]
