# Generated by Django 5.0.3 on 2024-05-01 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_alter_userprofile_station'),
    ]

    operations = [
        migrations.AddField(
            model_name='defect',
            name='defect_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='discrepancy_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='DefectResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of responsibility attributed to this employee.', max_digits=5)),
                ('defect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_responsibilities', to='production.defect')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='defect_responsibilities', to='production.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='defect',
            name='responsible_employees',
            field=models.ManyToManyField(through='production.DefectResponsibility', to='production.userprofile'),
        ),
        migrations.CreateModel(
            name='DiscrepancyResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of responsibility attributed to this employee.', max_digits=5)),
                ('discrepancy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_responsibilities', to='production.discrepancy')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discrepancy_responsibilities', to='production.userprofile')),
            ],
        ),
        migrations.AddField(
            model_name='discrepancy',
            name='responsible_employees',
            field=models.ManyToManyField(through='production.DiscrepancyResponsibility', to='production.userprofile'),
        ),
    ]
