# Generated by Django 5.0.3 on 2025-02-11 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0019_alter_clientorder_order_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production.color', verbose_name='Цвет')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production.fabrics', verbose_name='Ткань')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batches', to='production.order', verbose_name='Модель')),
            ],
        ),
        migrations.CreateModel(
            name='SizeBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=10, verbose_name='Размер')),
                ('quantity', models.IntegerField(verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_batches', to='production.batch', verbose_name='Группа')),
            ],
        ),
        migrations.AddField(
            model_name='cut',
            name='size_batches',
            field=models.ManyToManyField(blank=True, null=True, related_name='cuts', through='production.CutSize', to='production.sizebatch', verbose_name='Размеры и количества'),
        ),
        migrations.AddField(
            model_name='cutsize',
            name='size_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cut_sizes', to='production.sizebatch', verbose_name='Размер и количество'),
        ),
        migrations.AddField(
            model_name='passport',
            name='size_batches',
            field=models.ManyToManyField(blank=True, null=True, related_name='passports', through='production.PassportSize', to='production.sizebatch', verbose_name='Размеры и количества'),
        ),
        migrations.AddField(
            model_name='passportsize',
            name='size_batches',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='passport_sizes', to='production.sizebatch', verbose_name='Размер и количество'),
        ),
    ]
