# Generated by Django 5.0.3 on 2025-02-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_batch_sizebatch_cut_size_batches_cutsize_size_batch_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cut',
            name='size_batches',
            field=models.ManyToManyField(related_name='cuts', through='production.CutSize', to='production.sizebatch', verbose_name='Размеры и количества'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='size_batches',
            field=models.ManyToManyField(related_name='passports', through='production.PassportSize', to='production.sizebatch', verbose_name='Размеры и количества'),
        ),
    ]
