# Generated by Django 5.0.3 on 2024-03-31 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_alter_userprofile_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='work',
            old_name='user',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='model',
        ),
        migrations.AddField(
            model_name='model',
            name='operations',
            field=models.ManyToManyField(related_name='models', to='production.operation'),
        ),
        migrations.AlterField(
            model_name='employeeattendance',
            name='is_clock_in',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='assortment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.assortment'),
        ),
        migrations.AlterField(
            model_name='order',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.client'),
        ),
        migrations.AlterField(
            model_name='order',
            name='model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.model'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='roll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='production.roll'),
        ),
        migrations.AlterField(
            model_name='passport',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passports', to='production.order'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='work',
            name='passport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='production.passport'),
        ),
        migrations.AlterField(
            model_name='work',
            name='size_quantity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='works', to='production.sizequantity'),
        ),
    ]
