# Generated by Django 5.0.3 on 2025-02-25 20:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstractaccessory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='accessoryattribute',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='assortment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='branch',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientorder',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='color',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='consumption',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cut',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cutsize',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employeeattendance',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equipment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='error',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='errorresponsibility',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fabrics',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fixedsalary',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='model',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modelaccessory',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='modeloperation',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='node',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operation',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passport',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='passportsize',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='phonenumberscaner',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productionpiece',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reassignedwork',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='roll',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='salarypayment',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sizequantity',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprofile',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='work',
            name='company',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='production.company'),
            preserve_default=False,
        ),
    ]
