# Generated by Django 5.0.3 on 2024-05-01 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0020_defect_defect_cost_discrepancy_discrepancy_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='defect',
            old_name='defect_cost',
            new_name='cost',
        ),
        migrations.RenameField(
            model_name='discrepancy',
            old_name='discrepancy_cost',
            new_name='cost',
        ),
    ]
