# Generated by Django 5.0.3 on 2024-05-05 04:01

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_rename_defect_cost_defect_cost_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.CharField(choices=[('DEFECT', 'Defect'), ('DISCREPANCY', 'Discrepancy')], max_length=20)),
                ('defect_type', models.CharField(blank=True, choices=[('STITCHING', 'Stitching Error'), ('CUTTING', 'Cutting Error'), ('FABRIC', 'Fabric Defect'), ('ASSEMBLY', 'Assembly Error'), ('OTHER', 'Other Error')], max_length=20, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('UNRESOLVABLE', 'Unresolvable'), ('RESOLVED', 'Resolved')], default='REPORTED', max_length=20)),
                ('reported_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('resolved_date', models.DateTimeField(blank=True, null=True)),
                ('passport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='production.passport')),
                ('size_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='production.sizequantity')),
            ],
        ),
        migrations.CreateModel(
            name='ErrorResponsibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage', models.DecimalField(decimal_places=2, help_text='Percentage of responsibility attributed to this employee.', max_digits=5)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_responsibilities', to='production.userprofile')),
                ('error', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='error_responsibilities', to='production.error')),
            ],
        ),
        migrations.AddField(
            model_name='error',
            name='responsible_employees',
            field=models.ManyToManyField(through='production.ErrorResponsibility', to='production.userprofile'),
        ),
    ]
