# Generated by Django 5.0.3 on 2024-03-31 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_rename_user_work_employee_remove_operation_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='employee',
        ),
        migrations.CreateModel(
            name='AssignedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.userprofile')),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.work')),
            ],
        ),
        migrations.AddField(
            model_name='work',
            name='employees',
            field=models.ManyToManyField(related_name='assigned_works', through='production.AssignedWork', to='production.userprofile'),
        ),
    ]
