# Generated by Django 5.0.3 on 2025-02-11 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0021_alter_cut_size_batches_alter_passport_size_batches'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='contact_info',
        ),
    ]
