# Generated by Django 5.0.3 on 2025-02-27 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_remove_abstractaccessory_company_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Roll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('roll_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер рулона')),
                ('length_t', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длина Т (м)')),
                ('length_p', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длина П (м)')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина (м)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Вес (кг)')),
                ('remainder', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Остаток (м)')),
                ('is_used', models.BooleanField(default=False, verbose_name='Is Used')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.color', verbose_name='Цвет')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.company')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.fabrics', verbose_name='Ткань')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.supplier', verbose_name='Поставщик')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
