# Generated by Django 5.0.3 on 2024-04-01 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_remove_work_employee_assignedwork_work_employees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='work',
            name='start_time',
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignedwork',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='assignedwork',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_tasks', to='production.userprofile'),
        ),
        migrations.AlterField(
            model_name='assignedwork',
            name='work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_works', to='production.work'),
        ),
    ]
