# Generated by Django 5.0.3 on 2024-05-05 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_error_errorresponsibility_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='defectresponsibility',
            name='defect',
        ),
        migrations.RemoveField(
            model_name='defectresponsibility',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='discrepancy',
            name='passport',
        ),
        migrations.RemoveField(
            model_name='discrepancy',
            name='responsible_employees',
        ),
        migrations.RemoveField(
            model_name='discrepancy',
            name='size_quantity',
        ),
        migrations.RemoveField(
            model_name='discrepancyresponsibility',
            name='discrepancy',
        ),
        migrations.RemoveField(
            model_name='discrepancyresponsibility',
            name='employee',
        ),
        migrations.DeleteModel(
            name='Defect',
        ),
        migrations.DeleteModel(
            name='DefectResponsibility',
        ),
        migrations.DeleteModel(
            name='Discrepancy',
        ),
        migrations.DeleteModel(
            name='DiscrepancyResponsibility',
        ),
    ]
