# Generated by Django 5.0.3 on 2025-02-11 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0022_remove_client_contact_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizequantity',
            name='fabrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.fabrics', verbose_name='Ткань'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='quantity',
            field=models.IntegerField(blank=True, null=True, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='size',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Размер'),
        ),
    ]
