# Generated by Django 5.0.3 on 2024-04-01 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_remove_work_end_time_remove_work_start_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignedwork',
            name='is_success',
            field=models.BooleanField(default=False, verbose_name='Completed Successfully'),
        ),
    ]
