# Generated by Django 5.0.3 on 2025-02-12 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_sizequantity_fabrics_alter_sizequantity_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='number',
        ),
        migrations.RemoveField(
            model_name='node',
            name='type',
        ),
        migrations.RemoveField(
            model_name='operation',
            name='employee',
        ),
    ]
