# Generated by Django 5.0.3 on 2025-02-27 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0023_supplier_roll'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roll',
            old_name='roll_number',
            new_name='name',
        ),
    ]
