# Generated by Django 5.0.3 on 2025-02-12 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_remove_node_number_remove_node_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operation',
            name='average_completion_time',
        ),
    ]
