# Generated by Django 5.0.3 on 2024-04-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_assignedwork_is_success'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='employees',
            field=models.ManyToManyField(through='production.AssignedWork', to='production.userprofile'),
        ),
    ]
