# Generated by Django 5.0.3 on 2025-02-28 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0024_rename_roll_number_roll_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='cut_year',
            field=models.PositiveIntegerField(default=2025),
        ),
        migrations.AddField(
            model_name='company',
            name='last_cut_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='company',
            name='last_operation_number',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='color',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='fabrics',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='node',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AddConstraint(
            model_name='color',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_color_per_company'),
        ),
        migrations.AddConstraint(
            model_name='equipment',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_equipment_per_company'),
        ),
        migrations.AddConstraint(
            model_name='fabrics',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_fabric_per_company'),
        ),
        migrations.AddConstraint(
            model_name='node',
            constraint=models.UniqueConstraint(fields=('company', 'name'), name='unique_node_per_company'),
        ),
    ]
