# Generated by Django 5.0.3 on 2025-02-28 17:33

import production.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_company_cut_year_company_last_cut_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='cut_year',
            field=models.PositiveIntegerField(default=production.models.Company.current_year),
        ),
    ]
