# Generated by Django 5.0.3 on 2025-02-12 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_remove_operation_average_completion_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sizebatch',
            name='batch',
        ),
        migrations.RemoveField(
            model_name='passport',
            name='size_batches',
        ),
        migrations.RemoveField(
            model_name='passportsize',
            name='size_batches',
        ),
        migrations.RemoveField(
            model_name='cutsize',
            name='size_batch',
        ),
        migrations.RemoveField(
            model_name='cut',
            name='size_batches',
        ),
        migrations.DeleteModel(
            name='Batch',
        ),
        migrations.DeleteModel(
            name='SizeBatch',
        ),
    ]
