# Generated by Django 5.0.3 on 2024-04-02 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0025_alter_work_employees'),
    ]

    operations = [
        migrations.AddField(
            model_name='operation',
            name='average_completion_time',
            field=models.IntegerField(null=True),
        ),
    ]
