# Generated by Django 5.0.3 on 2025-02-14 08:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_remove_sizebatch_batch_remove_passport_size_batches_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productionpiece',
            name='defect_type',
        ),
    ]
