# Generated by Django 5.0.3 on 2025-03-01 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_remove_userprofile_unique_employee_id_per_branch_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='passports', to='production.roll', verbose_name='Roll'),
        ),
    ]
