# Generated by Django 5.0.3 on 2024-04-03 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0026_operation_average_completion_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='passport',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='Passport Completed'),
        ),
    ]
