# Generated by Django 5.0.3 on 2025-03-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_passport_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='consumption_p',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Расход П'),
        ),
    ]
