# Generated by Django 5.0.3 on 2025-02-14 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0027_remove_productionpiece_defect_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='cut',
            name='consumption',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Расход'),
        ),
        migrations.AddField(
            model_name='cut',
            name='length',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Длина'),
        ),
        migrations.AddField(
            model_name='cut',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Ширина'),
        ),
    ]
