# Generated by Django 5.0.3 on 2025-03-03 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_cut_consumption_p'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roll',
            name='remainder',
        ),
        migrations.AddField(
            model_name='roll',
            name='original_roll',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='remainders', to='production.roll', verbose_name='Original Roll'),
        ),
    ]
