# Generated by Django 5.0.3 on 2025-02-14 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0028_cut_consumption_cut_length_cut_width'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='station',
            field=models.CharField(blank=True, choices=[('admin_technologist', 'Админ/Технолог'), ('cutting_station', 'Закройный участок'), ('sewing_station', 'Швейный участок'), ('ironing_station', 'Утюжный участок'), ('quality_control', 'ОТК'), ('package', 'Упаковка'), ('warehouse', 'Склад'), ('interns', 'Практиканты'), ('others', 'Остальные')], default='sewing_station', max_length=100, null=True, verbose_name='Станция'),
        ),
    ]
