# Generated by Django 5.0.3 on 2025-03-13 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_remove_roll_remainder_roll_original_roll'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizequantity',
            name='checked',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверено'),
        ),
        migrations.AddField(
            model_name='sizequantity',
            name='packed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Упаковано'),
        ),
    ]
