# Generated by Django 5.0.3 on 2025-02-14 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0029_alter_userprofile_station'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Статус'),
        ),
    ]
