# Generated by Django 5.0.3 on 2025-03-13 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_sizequantity_checked_sizequantity_packed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='quantity',
            field=models.IntegerField(default=0, verbose_name='Количество'),
        ),
    ]
