# Generated by Django 5.0.3 on 2025-02-14 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0030_alter_userprofile_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.BooleanField(blank=True, default=True, null=True, verbose_name='Статус'),
        ),
    ]
