# Generated by Django 5.0.3 on 2025-03-13 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0031_alter_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportsize',
            name='factual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Факт'),
        ),
    ]
