# Generated by Django 5.0.3 on 2025-03-29 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0032_passportsize_factual'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizequantity',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Технолог'), (2, 'Швея'), (3, 'Закройщик'), (4, 'ОТК'), (5, 'Упаковщик'), (6, 'Кладовщик')], default=2, verbose_name='Тип'),
        ),
    ]
