# Generated by Django 5.0.3 on 2025-03-30 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0033_sizequantity_sku_alter_userprofile_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивировано')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.company')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='production.model', verbose_name='Модель')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='production.stock', verbose_name='Сырьё/Комплектующие')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
