# Generated by Django 5.0.3 on 2025-04-01 14:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0034_stock_billofmaterials'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='company',
        ),
        migrations.DeleteModel(
            name='BillOfMaterials',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
