# Generated by Django 5.0.3 on 2025-03-30 06:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0034_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='BillOfMaterials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_archived', models.BooleanField(default=False, verbose_name='Архивировано')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='production.model', verbose_name='Модель')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='production.stock', verbose_name='Сырьё/Комплектующие')),
            ],
        ),
    ]
