# Generated by Django 5.0.3 on 2025-03-30 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0035_alter_stock_quantity_billofmaterials'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_archived',
            field=models.BooleanField(default=False, verbose_name='Is Archived'),
        ),
    ]
