# Generated by Django 5.0.3 on 2025-03-30 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0036_stock_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='quantity',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
