# Generated by Django 5.0.3 on 2025-04-05 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0036_item_billofmaterials_stock_warehouse_stockmovement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passportsize',
            name='checked',
            field=models.IntegerField(blank=True, null=True, verbose_name='Проверено'),
        ),
        migrations.AddField(
            model_name='passportsize',
            name='packed',
            field=models.IntegerField(blank=True, null=True, verbose_name='Упаковано'),
        ),
        migrations.AddField(
            model_name='passportsize',
            name='sku',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='SKU'),
        ),
        migrations.AddField(
            model_name='sizequantity',
            name='factual',
            field=models.IntegerField(blank=True, null=True, verbose_name='Факт'),
        ),
        migrations.DeleteModel(
            name='ProductionPiece',
        ),
    ]
