# Generated by Django 5.0.3 on 2025-04-06 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0037_passportsize_checked_passportsize_packed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passportsize',
            name='checked',
        ),
        migrations.RemoveField(
            model_name='passportsize',
            name='packed',
        ),
    ]
