# Generated by Django 5.0.3 on 2025-04-06 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0038_remove_passportsize_checked_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cut',
            name='consumption_p',
        ),
        migrations.AddField(
            model_name='model',
            name='consumption_p',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Расход Практический'),
        ),
        migrations.AddField(
            model_name='model',
            name='consumption_t',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Расход Теоретический'),
        ),
    ]
