# Generated by Django 5.0.3 on 2025-04-13 13:42

import django.db.models.deletion
from django.db import migrations, models

def populate_sizequantity_model(apps, schema_editor):
    SizeQuantity = apps.get_model('production', 'SizeQuantity')
    Order = apps.get_model('production', 'Order')
    
    # Iterate over all SizeQuantity records.
    for sq in SizeQuantity.objects.all():
        # Find orders that use this SizeQuantity.
        # This assumes a SizeQuantity is linked to Order via the many-to-many field.
        # You could refine this to choose a specific order if there are multiple.
        orders = Order.objects.filter(size_quantities=sq)
        if orders.count() == 1:
            order = orders.first()
            sq.model_id = order.model_id
            sq.save(update_fields=['model'])
        else:
            # Handling multiple orders referencing the same SizeQuantity:
            # For instance, if there are multiple, pick the first or log a warning.
            if orders.exists():
                order = orders.first()
                sq.model_id = order.model_id
                sq.save(update_fields=['model'])
            # Otherwise, leave it as None if no associated order is found.

class Migration(migrations.Migration):

    dependencies = [
        ('production', '0039_remove_cut_consumption_p_model_consumption_p_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizequantity',
            name='model',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.model', verbose_name='Модель'),
        ),
        migrations.RunPython(populate_sizequantity_model),
    ]
