# Generated by Django 5.0.3 on 2025-04-13 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0040_sizequantity_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizequantity',
            name='production_complete',
            field=models.BooleanField(default=False, verbose_name='Производство завершено'),
        ),
    ]
