# Generated by Django 5.0.3 on 2025-04-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0041_sizequantity_production_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='type',
            field=models.IntegerField(choices=[(0, 'Сырье'), (1, 'Готовая продукция')], default=0, verbose_name='Тип'),
        ),
    ]
