# Generated by Django 5.0.3 on 2025-04-17 01:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0042_stock_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterials',
            name='model',
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='sizequantity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='production.sizequantity', verbose_name='Модель'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.color', verbose_name='Цвет'),
        ),
        migrations.AddField(
            model_name='item',
            name='fabrics',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.fabrics', verbose_name='Ткань'),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('name', models.CharField(max_length=255)),
                ('is_archived', models.BooleanField(default=False, verbose_name='Is Archived')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.company')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='production.category', verbose_name='Категория'),
        ),
    ]
