# Generated by Django 5.0.3 on 2025-04-17 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0043_remove_billofmaterials_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='unit',
        ),
        migrations.AddField(
            model_name='item',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
