# Generated by Django 5.0.3 on 2025-04-18 12:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0044_remove_stock_unit_item_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='color',
        ),
        migrations.RemoveField(
            model_name='item',
            name='fabrics',
        ),
        migrations.CreateModel(
            name='RollBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('width', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество рулонов')),
                ('color', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.color')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.company')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.fabrics')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.supplier')),
            ],
            options={
                'unique_together': {('color', 'fabric', 'supplier', 'width')},
            },
        ),
        migrations.AddField(
            model_name='roll',
            name='roll_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.rollbatch', verbose_name='Рулоны'),
        ),
    ]
