# Generated by Django 5.0.3 on 2025-04-18 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0045_remove_item_color_remove_item_fabrics_rollbatch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollbatch',
            name='quantity',
        ),
        migrations.AddField(
            model_name='rollbatch',
            name='unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='type',
            field=models.IntegerField(choices=[(0, 'Сырье'), (1, 'Готовая продукция'), (2, 'Рулоны')], default=0, verbose_name='Тип'),
        ),
    ]
