# Generated by Django 5.0.3 on 2025-04-23 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0046_remove_rollbatch_quantity_rollbatch_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rollbatch',
            name='unit',
        ),
        migrations.AddField(
            model_name='sizequantity',
            name='shipment_complete',
            field=models.BooleanField(default=False, verbose_name='Отправка завершено'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'Новый'), (1, 'В процессе'), (2, 'Завершен'), (3, 'Отправлен')], default=0, verbose_name='Статус'),
        ),
    ]
