# Generated by Django 5.0.3 on 2025-04-23 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0047_remove_rollbatch_unit_sizequantity_shipment_complete_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizequantity',
            name='shipped',
            field=models.IntegerField(blank=True, null=True, verbose_name='Отправлено'),
        ),
    ]
