# Generated by Django 5.0.3 on 2025-04-23 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0048_sizequantity_shipped'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehouse',
            name='address',
        ),
    ]
