# Generated by Django 5.0.3 on 2025-04-26 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0050_costrecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Технолог'), (2, 'Швея'), (3, 'Закройщик'), (4, 'ОТК'), (5, 'Упаковщик'), (6, 'Кладовщик'), (7, 'Бухгалтер')], default=2, verbose_name='Тип'),
        ),
    ]
