# Generated by Django 5.0.3 on 2025-04-27 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('production', '0051_alter_userprofile_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billofmaterials',
            name='item',
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='content_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='object_id',
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
