# Generated by Django 5.0.3 on 2025-04-28 00:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0052_remove_billofmaterials_item_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='roll_batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.item', verbose_name='Рулоны'),
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='billofmaterials',
            name='object_id',
        ),
        migrations.AddField(
            model_name='billofmaterials',
            name='item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='bill_of_materials', to='production.item', verbose_name='Сырьё/Комплектующие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.color'),
        ),
        migrations.AddField(
            model_name='item',
            name='fabric',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.fabrics'),
        ),
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.supplier'),
        ),
        migrations.AddField(
            model_name='item',
            name='type',
            field=models.IntegerField(choices=[(0, 'Raw Material'), (1, 'Roll Material')], default=0, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='item',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.DeleteModel(
            name='RollBatch',
        ),
    ]
