# Generated by Django 5.0.3 on 2025-04-28 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0053_alter_roll_roll_batch_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='type',
        ),
        migrations.AddField(
            model_name='category',
            name='is_fabric',
            field=models.BooleanField(default=False, verbose_name='Is Fabric'),
        ),
    ]
