# Generated by Django 5.0.3 on 2025-05-14 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0054_remove_item_type_category_is_fabric'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='model',
            name='consumption_p',
        ),
        migrations.RemoveField(
            model_name='model',
            name='consumption_t',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='type',
            field=models.IntegerField(choices=[(0, 'Администратор'), (1, 'Технолог'), (2, 'Швея'), (3, 'Закройщик'), (4, 'ОТК'), (5, 'Упаковщик'), (6, 'Кладовщик'), (7, 'Бухгалтер'), (8, 'Младший Технолог')], default=2, verbose_name='Тип'),
        ),
    ]
