# Generated by Django 5.0.3 on 2025-06-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0055_remove_model_consumption_p_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('reported_qty', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сообщённое кол-во')),
                ('confirmed_qty', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Подтверждённое кол-во')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed')], default='draft', max_length=10, verbose_name='Статус')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата проведения в склад')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.company')),
                ('size_quantity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='production.sizequantity', verbose_name='Размер-кол-во')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
