# Generated by Django 5.0.3 on 2025-07-14 01:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0056_productionreceipt'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.client'),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Последняя цена закупки'),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_supplied_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата последней поставки'),
        ),
    ]
