# Generated by Django 5.0.3 on 2025-07-14 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0057_item_client_stock_last_cost_stock_last_supplied_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.client', verbose_name='Клиент'),
        ),
    ]
