# Generated by Django 5.0.3 on 2025-07-14 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0058_roll_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
