# Generated by Django 5.0.3 on 2025-09-02 18:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0059_client_description_supplier_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreceipt',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='productionreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.supplier', verbose_name='Поставщик'),
        ),
        migrations.AddField(
            model_name='stock',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.client', verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='stock',
            name='last_supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='production.supplier', verbose_name='Последний поставщик'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='production_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='production.productionreceipt'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='reason',
            field=models.CharField(blank=True, choices=[('purchase', 'Purchase'), ('prod_receipt', 'Production Receipt'), ('consume', 'Consume'), ('transfer', 'Transfer'), ('cycle_count', 'Cycle Count'), ('damage', 'Damage'), ('return_supplier', 'Return to Supplier'), ('return_customer', 'Customer Return'), ('correction', 'Correction')], max_length=32, null=True),
        ),
        migrations.CreateModel(
            name='MaterialReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('modified_at', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('reported_qty', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Reported quantity')),
                ('confirmed_qty', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Confirmed quantity')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('posted', 'Posted')], default='draft', max_length=10, verbose_name='Status')),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Posted at')),
                ('roll_no', models.CharField(blank=True, max_length=100, null=True, verbose_name='Roll number')),
                ('measured_length_m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Measured length (m)')),
                ('width_m', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Width (m)')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Weight (kg)')),
                ('lot_code', models.CharField(blank=True, max_length=100, null=True, verbose_name='Lot code')),
                ('note', models.TextField(blank=True, null=True, verbose_name='Note')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_receipts', to='production.client', verbose_name='Client')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.company')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_receipts', to='production.item', verbose_name='Item')),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_receipts', to='production.supplier', verbose_name='Supplier')),
                ('warehouse', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='material_receipts', to='production.warehouse', verbose_name='Warehouse')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='material_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movements', to='production.materialreceipt'),
        ),
    ]
