# Generated by Django 5.0.3 on 2025-09-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0060_productionreceipt_client_productionreceipt_supplier_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materialreceipt',
            name='lot_code',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='measured_length_m',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='roll_no',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='weight_kg',
        ),
        migrations.RemoveField(
            model_name='materialreceipt',
            name='width_m',
        ),
    ]
