# Generated by Django 5.0.3 on 2025-09-05 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0061_remove_materialreceipt_lot_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='materialreceipt',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Cost per unit'),
        ),
    ]
