# Generated by Django 5.0.3 on 2025-09-17 10:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0062_materialreceipt_cost'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Fabrics',
            new_name='Fabric',
        ),
        migrations.RenameField(
            model_name='sizequantity',
            old_name='fabrics',
            new_name='fabric',
        ),
    ]
