# Generated by Django 5.0.3 on 2025-09-18 04:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0063_rename_fabrics_fabric_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productionreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_receipts', to='production.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='material_receipts', to='production.item', verbose_name='Item'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_receipts', to='production.supplier', verbose_name='Supplier'),
        ),
        migrations.AlterField(
            model_name='materialreceipt',
            name='warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_receipts', to='production.warehouse', verbose_name='Warehouse'),
        ),
        migrations.AlterField(
            model_name='productionreceipt',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('confirmed', 'Confirmed'), ('posted', 'Posted')], default='draft', max_length=10, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='checked',
            field=models.PositiveIntegerField(default=0, verbose_name='Проверено'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='factual',
            field=models.PositiveIntegerField(default=0, verbose_name='Факт'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='packed',
            field=models.PositiveIntegerField(default=0, verbose_name='Упаковано'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='sizequantity',
            name='shipped',
            field=models.PositiveIntegerField(default=0, verbose_name='Отправлено'),
        ),
    ]
