# Generated by Django 5.0.3 on 2025-09-20 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0064_productionreceipt_warehouse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='assortments',
            field=models.ManyToManyField(blank=True, related_name='assortments', to='production.assortment', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='client',
            name='bank_account',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Расчетный счет'),
        ),
        migrations.AddField(
            model_name='client',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Контактные данные'),
        ),
        migrations.AddField(
            model_name='client',
            name='pin',
            field=models.IntegerField(blank=True, null=True, verbose_name='ИНН'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='categories', to='production.category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='contact_info',
            field=models.TextField(blank=True, null=True, verbose_name='Контактные данные'),
        ),
    ]
