# Generated by Django 5.0.3 on 2025-09-23 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0065_client_assortments_client_bank_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='pin',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='ИНН'),
        ),
    ]
