# Generated by Django 5.0.3 on 2025-09-26 04:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0066_alter_client_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roll',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='production.supplier', verbose_name='Поставщик'),
        ),
    ]
