# Generated by Django 5.0.3 on 2025-10-01 11:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0067_alter_roll_supplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='roll',
            name='material_receipt',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to='production.materialreceipt', verbose_name='Materials Receipt'),
        ),
    ]
